version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper"
      KAFKA_CREATE_TOPICS: "my-topic:2:1"
  kafka_manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: "zookeeper"
    ports:
      - "9000:9000"
  kafka_heartbeat:
    build:
      context: ./kafka_heartbeat
    volumes:
      - "./kafka_heartbeat:/usr/src/kafka_heartbeat"
    command: ["cargo", "run"]
