[package]
name = "kafka_heartbeat"
version = "0.1.0"
authors = ["rust"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.8.0"
ctrlc = "3.1.3"
log = "0.4"
stderrlog = "0.4.3"
